Upload .hyp files to joska's server
Also unify udo/hcp handling.

diff --git a/doc/Makefile b/doc/Makefile
--- a/doc/Makefile
+++ b/doc/Makefile
@@ -1,19 +1,27 @@
-UDO = udo
-HCP = hcp
+UDO ?= udo
+HCP ?= hcp
 
 LANGUAGES = en de fr
 
 IMAGES = cops.img
 
-.SUFFIXES: .hyp .u
-
 ALL_HYPS = $(addprefix cops_, $(addsuffix .hyp, $(LANGUAGES)))
 
 all: $(ALL_HYPS)
 
-.u.hyp:
-	$(UDO) --stg -o $(notdir $(basename $@)).stg $<
-	$(HCP) -o $@ $(notdir $(basename $@)).stg
+%.stg: %.u
+	@if command -v $(UDO) >/dev/null 2>&1; then \
+		$(UDO) --stg -o $@ $<; \
+	else \
+		echo "UDO not found, help file not compiled" >&2; \
+	fi
+
+%.hyp: %.stg
+	@if command -v $(HCP) >/dev/null 2>&1 && test -f $<; then \
+		$(HCP) -o $@ $<; \
+	else \
+		echo "HCP not found, help file not compiled" >&2; \
+	fi
 
 $(ALL_HYPS): $(IMAGES)
 
